### ISSUE TITLE
Missing flag

### ISSUE THREAD

**Issue by albertovincenzi** [qWici/vue-lang-code-flags#10]
Hello,
I've noticed that "ca" flag is missing
https://it.wikipedia.org/wiki/Catalogna#/media/File:Flag_of_Catalonia.svg

ISO standard is "ca" but flag is "es-ca".

Would be possible to add it?

**Comment by qWici** [comment]
@albertovincenzi added. New version of package available via Github registry. Now I try to setup action for publish package to NPM and Github at the same time. So if you use NPM registry - give me time =)

**Comment by albertovincenzi** [comment]
Great! I will see if NPM registry will be updated too so I can download the upgrade. Thanks a lot!

**Comment by albertovincenzi** [comment]
It seems npm registry don't get your updates. May I help you somehow?

**Comment by qWici** [comment]
@albertovincenzi updated. Close this issue if you successfully install update please.
