### ISSUE TITLE
all lang is correctly? 

### ISSUE THREAD

**Issue by dasawanaka** [qWici/vue-lang-code-flags#19]
In `relations.js` `am` is related to `am`. 
`am` lang is [Amharic](https://en.wikipedia.org/wiki/Amharic) - official language in [Ethiopia](https://en.wikipedia.org/wiki/Ethiopia) - ISO 3166 code `et` 
and 
`am` country is [Armenia](https://en.wikipedia.org/wiki/Armenia), official language is [Armenian](https://en.wikipedia.org/wiki/Armenian_language) ISO 639-1  `hy`

I don't think they should be connected like that

**Comment by dasawanaka** [comment]
- [ ] `ca`  is [Catalan_language](https://en.wikipedia.org/wiki/Catalan_language) in [Catalonia](https://en.wikipedia.org/wiki/Catalonia) code `ES-CT` in file is `es-ca`
- [ ] same lang `et` -> lang: estonian -> flag: estonia(ee) in file `et`
- [ ] lang `ha` -> hausa -> niger(`ne`) -> in file `ng`
- [ ] `km` -> Cambodian -> Cambodia(`kh`) -> in file `km`


based on [lang codes](https://meta.wikimedia.org/wiki/Template:List_of_language_names_ordered_by_code)

**Comment by qWici** [comment]
@dasawanaka merged. Many thanks!
