### ISSUE TITLE
Missing USA flag

### ISSUE THREAD

**Issue by saniales** [qWici/vue-lang-code-flags#5]
the United states flag (which is quite common) is missing, please add it

**Comment by qWici** [comment]
@saniales this package provide flags of the country which the language comes from. The main purpose of this package is to show the flag that is applicable to the user as language designations. For example, if you have many articles in different languages and to make it easier for the user to visually filter the list of articles, you can show a flag that matches the language of the article. If you need exactly the flags of the countries - this package is not the best choice. Check [this](https://www.npmjs.com/package/vue-flag-icon) one.
